version: '2'  # specify docker-compose version

# Define the services/containers to be run
services:
  mainserver: # name of the first service
    image: rmaierlit/compose_demo:mainserver
    ports:
      - "3000:3000" # specify port forewarding
    links:
      - dbserver
  dbserver: # name of the second service
    image: rmaierlit/compose_demo:dbserver
    ports:
      - "5000:5000" # specify port forewarding
    links:
      - mysql
  mysql: # name of the third service
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dockerDemo
      MYSQL_DATABASE: dockerDemo
    ports:
      - "3306:3306"
